### ISSUE TITLE
(Warning) upgrade CodeQL Action v1 to v2  

### ISSUE THREAD

**Issue by ayadim** [projectdiscovery/nuclei-action#35]
hi,
each time I execute the nuclei-action I get this warning.
```
Warning: CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
Error: codeql/upload-sarif action failed: HttpError: Resource not accessible by integration
```

I guess the CodeQL version needs to be updated.
```github/codeql-action/upload-sarif@v1
````
regards.

**Comment by ayadim** [comment]
any updates ?

**Comment by ehsandeep** [comment]
@ayadim, it means you need to update your action file if you are using that specific action, it's unrelated to `nuclei-action` project, but I've updated the readme example - https://github.com/projectdiscovery/nuclei-action/commit/bc4220f05de63acaf2b29a96fd61a2128dd2bd94

**Comment by ayadim** [comment]
Hi,

@ehsandeep  i get new error (idk if i need to create new issue) : 
``
nuclei-scan
codeql/upload-sarif action failed: HttpError: Resource not accessible by integration
```

can you test the action? I tried many examples in the readme, some of them work but I did not get the output file.

regards
