### ISSUE TITLE
Unable to upload "nuclei.sarif" as it is not valid SARIF

### ISSUE THREAD

**Issue by schniggie** [projectdiscovery/nuclei-action#43]
Hi guys,

just tried the default example workflow with dshboard alerts [nuclei.yaml](https://github.com/schniggie/vuln-mgmt/blob/main/.github/workflows/nuclei.yml). But it fails on `github/codeql-action/upload-sarif@v2`. 
See full error here: https://github.com/schniggie/vuln-mgmt/actions/runs/3383544249

**Comment by ehsandeep** [comment]
@schniggie thanks for flagging this, this is now being tracked here - https://github.com/projectdiscovery/nuclei/issues/2608#issuecomment-1301742901
