### ISSUE TITLE
Issues with workflow files

### ISSUE THREAD

**Issue by hakrishi** [projectdiscovery/nuclei-action#48]
Hi there,

When using the `workflow: ./github/workflow.yml` line, the Action does not pick up the workflow. I noticed this issue only occurs when the workflow file extension is .yml. It works perfectly fine using the .yaml extension. Just thought I raise this issue here. 

Kind regards

RIshi

**Comment by ehsandeep** [comment]
@hakrishi `.yaml` is the only valid extension recognized by nuclei engine to avoid confusion between both.

**Comment by hakrishi** [comment]
Thanks for the clarification, feel free to close this issue 🙂
