### ISSUE TITLE
Infrequent error: "Cannot read properties of undefined (reading 'replace')"

### ISSUE THREAD

**Issue by allanbreyes** [projectdiscovery/nuclei-action#51]
Hi, team! We infrequently receive an error, maybe ~1-5% of the time:

> Error: Cannot read properties of undefined (reading 'replace')

There's only 3 places in the codebase that call `.replace`, and I suspect it's the call to [getLatestInfo](https://github.com/projectdiscovery/nuclei-action/blob/6fdcee9529d5da992b2e9a4b599ee7688d145ed2/src/installer.js#L39) sometimes having a transient error. I think it probably needs a retry, or at least some slightly better error-handling and logging. I can take a stab at it if I have some free cycles next week. Thoughts?

**Comment by CCDi** [comment]
Hi team! Any thoughts/updates on this error? We bumped into it once again! 🙏

**Comment by RamanaReddy0M** [comment]
@CCDi added existence checks before applying `replace(..)`
> Error: Cannot read properties of undefined (reading 'replace')

will fixed with https://github.com/projectdiscovery/nuclei-action/pull/88
