### ISSUE TITLE
Allow pinning nuclei version

### ISSUE THREAD

**Issue by dkarlinsky** [projectdiscovery/nuclei-action#69]
Currently it looks like the latest version is always installed, which can be problematic when a new version with possibly breaking changes is released.
We just saw our workflow break, apparently because something changed in version `3.0.0` 
It would be useful to allow passing the desired nuclei version to this action.

I can submit a PR, if this will help

**Comment by dkarlinsky** [comment]
@dogancanbakir are you one of the maintainers? 
Does the 👍 mean I should submit a PR? 😃

**Comment by dogancanbakir** [comment]
@dkarlinsky,
Hey there! Feel free to raise a PR, and I'll review it.
