### ISSUE TITLE
Allowing the use of Nuclei without providing target flag

### ISSUE THREAD

**Issue by alwashali** [projectdiscovery/nuclei-action#93]
Hello team

Currently execution will fail if target flag is not provided. I need to use nuclei flags without doing actual scan hence there is no target to provide 

Example 
- validate, update templates ..etc 
- Running all templates where each template has different target 

Is it possible to make the target flag optional 

Thanks

**Comment by GeorginaReeder** [comment]
Thanks so much for this @alwashali , we'll take a look into it!

**Comment by dwisiswant0** [comment]
You can use our composite action [**`projectdiscovery/actions/setup/nuclei`**](https://github.com/projectdiscovery/actions/tree/master/setup/nuclei) as a workaround if you only need the binary.
